// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlunxjducysxwilxrlwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsdW54amR1Y3lzeHdpbHhybHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDkwNDEsImV4cCI6MjA3Mzg4NTA0MX0.ZI4VxF4OCwSPmaL3QOgnFKEJsxPtOfNQu-m2JXbB0H8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});